apiVersion: v2
name: cert-manager
description: Cert Manager Helm Chart
type: application
version: 0.1.0
appVersion: "v1.19.3"
dependencies:
  - name: cert-manager
    version: v1.19.3
    repository: https://charts.jetstack.io/