apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: cicd
spec:
  template:
    metadata:
      labels:
        app: cicd
    spec:
      expireAfter: 24h
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: cicd
      taints:
        - effect: NoSchedule
          key: cicd
          value: "true"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 3600s
